### ISSUE TITLE
Data review questions November 13, 2020

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/ummzi#1]
@jhpoelen @seltmann reviewed this dataset on November 13, 2020. Questions from this review include:

1.  11448 source taxon names are null. Many of these also include a target taxon name that is null and the only data is a uuid for the record. Does this make sense and do you expect skeleton records to exist in the dataset?

1.  When will the data be updated? Currently, we have a [snapshot](https://github.com/globalbioticinteractions/ummzi/blob/master/ummzi-full-database-export.csv.gz) from January 21, 2020.

1. All interactions are hasHost and they are mapped to http://purl.obolibrary.org/obo/RO_0002454

A full review is found at https://www.globalbioticinteractions.org/parasitetracker:

Review of [globalbioticinteractions/ummzi] included:
  - 67819 interaction(s)
  - 340820 note(s)
  - 67819 info(s)
[globalbioticinteractions/ummzi] has 340820 reviewer note(s):
 317711 target taxon name missing
  11448 source taxon name missing: using institutionCode/collectionCode/collectionId/catalogNumber/occurrenceId as placeholder
  11448 source taxon name missing
    213 target taxon name missing: using institutionCode/collectionCode/collectionId/catalogNumber/occurrenceId as placeholder

**Comment by seltmann** [comment]
After discussion with Erika Tucker about the review and continuing to look at the UMMZI data in Darwin Core IPT (https://ipt.lsa.umich.edu/archive.do?r=ummz_insects) GloBI will get a direct data export from Specify as it is richer in data and more granular.

1. Erika will upload the raw data from the Specify database into a google drive folder
1. Erika will send link information to Jorrit
1. Jorrit will use that link to download the file and index in GloBI
1. Will implement another review

Erika will update the same file repeatedly to create new updates in GloBI.

**Comment by jhpoelen** [comment]
@seltmann Erika complete steps 1. and 2. soon after the review!

When attempting 3. (point to google drive location, and index new version), I ended up doing the following.

First, I tried to link directly into google drive. But alas, due to the file size (~160MB) the direct links no longer work because google claims that it can't scan for viruses on download. 

So, I worked around this limitation by manually downloading the datasets, and adding it as a gzipped file to https://github.com/globalbioticinteractions/ummzi. 

Lesson learned - Google Drive is not suitable/designed as a data publication platforms. Need to revisit the publication method in next review.

Also, I found that the schema of the UMMZI changed: there are now more fields / columns that provide useful information. I updated the schema mapping in globi.json . 

I was particularly excited about the field "1,93.collectionobjectattribute.text19", which, according to the field documentation she provided (see https://github.com/globalbioticinteractions/ummzi) is said to document the interaction type. However, it appears that all the field values were empty.

Ideally, we'd have the UMMZI data define/expose their own interaction types, so that GloBI (or any other re-user) can make an explicit mapping from the UMMZI interaction type to another scheme like the Relations Ontology.  

@seltmann - please let me know how you'd like to coordinate the follow-up data review to address data integration notes that came about.

**Comment by jhpoelen** [comment]
@seltmann note that I just had to change the date format because the newer data set uses the common US date notation (MM/dd/YYYY) instead of the previously used ISO8601 compatible (YYYY-MM-dd) format.

**Comment by jhpoelen** [comment]
and, this date formatting issue is causing parsing issue when dealing with partials (e.g., ```05/1923```, ```1877```) which appears to be formatted as MM/YYYY or as YYYY.

**Comment by jhpoelen** [comment]
@seltmann Prior to the data upgrade we had:

```
Review of [globalbioticinteractions/ummzi] included:
  - 67819 interaction(s)
  - 340820 note(s)
  - 67819 info(s)
```

Now, we have:

```
Review of [globalbioticinteractions/ummzi] included:
  - 86454 interaction(s)
  - 368684 note(s)
  - 86454 info(s)
```

almost 20k more interactions!

**Comment by seltmann** [comment]
@jhpoelen I think we can continue the work to review this dataset during the next meeting and create another list of possible modifications to the data and workflow. So far:

1. date formatting issues
2. discussion about interaction type. Are they intentionally blank?
3. workflow for Erika to zip and upload new updates to https://github.com/globalbioticinteractions/ummzi
4. review with Erika new schema mapping

**Comment by EMTuckerLab** [comment]
In reference to 3. - Would I then just upload the datafile to the "globi.json" that says its a placeholder to streamline the process? Or thats still on the to-do-list and I should wait for 4.?

**Comment by EMTuckerLab** [comment]
@jhpoelen in regard to the ""1,93.collectionobjectattribute.text19" - we put the relationship field in before one of our TCN workshops and I think we may have made it too expert specific (right now options in the field are things like permanent parasite, temporary parasite, mutualistic, pollinator of). These are useful to Barry when the biology is know, but since our technicians don't know that and are the ones entering the data, we need to change it to something more like "found on; ex.; host=; attached to; etc." We'll probably end up adding an attentional field and not deleting this one though, since I think it would still be super helpful for research once its filled out...

**Comment by seltmann** [comment]
Hello! @EMTuckerLabUMMZ 

You can upload new archive files using just the upload button on the front page. @jhpoelen did you have preferences as what kind of archive?

<img width="1139" alt="Screen Shot 2020-11-24 at 11 54 15 AM" src="https://user-images.githubusercontent.com/1044474/100144804-2e0e1880-2e4c-11eb-9bc7-a17a2a90ba99.png">

**Comment by jhpoelen** [comment]
hey @EMTuckerLabUMMZ @seltmann -

Using the upload button sounds like a good idea: using the basic GitHub WebUI you can update the existing file UMMZI-data-download.csv.gz by deleting the old one and uploading the new one with the exact same name. I've invited you as a contributor. After accepting the invite, you should be able to make changes. 

I'd prefer if you use gzip to compress the csv export. If you are using windows, you can use 7-Zip to create a gzip compressed file. Or search on "compress a file using gzip"

Happy to clarify/help if needed,

-jorrit

**Comment by jhpoelen** [comment]
Am closing this issue to prepare for migrating to https://github.com/EMTuckerLabUMMZ/ummzi .
